name: global

services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    ports:
      - "3000:3000"

    volumes:
      - /opt/docker/global/management/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock # listening on the docker socket to detect any container

    env_file:
      - .env
      - config/.env

    networks:
      - global-network

    labels:
      tsdproxy.enable: "true"
      tsdproxy.port.1: "443/https:3000/http"
      tsdproxy.name: "homepage"
