name: global

networks:
  global-network:
    driver: bridge

include:

  # Management
  - management/portainer/compose.yaml
  - management/homepage/compose.yaml

  # Productivity
  - productivity/filebrowser/compose.yaml
  - productivity/it-tools/compose.yaml

  # Network
  - network/tsdproxy/compose.yaml
  - network/open-port-finder/compose.yaml
  - network/caddy/compose.yaml
