name: global

networks:
  global-network:
    driver: bridge

include:

  # Management
  - infra/management/portainer/compose.yaml
  - infra/management/homepage/compose.yaml

  # Productivity
  - infra/productivity/filebrowser/compose.yaml
  - infra/productivity/it-tools/compose.yaml
  - infra/productivity/open-port-finder/compose.yaml

  # Network
  - infra/network/tsdproxy/compose.yaml
  - infra/network/caddy/compose.yaml
