name: public

services:
  open-port-finder:
    container_name: open-port-finder
    image: jasonc/open-port-finder:latest

    restart: unless-stopped

    labels:
      tsdproxy.enable: "true"
      tsdproxy.port.1: "443/https:56789/http"
      tsdproxy.name: "open-port-finder"

    network_mode: host # will use the same ip address of the host network, with the host's port
