name: app

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 9000:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data/conf.d:/etc/mysql/conf.d
      - ./data/logs:/logs
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
    networks:
      - global-network

volumes:
  mysql-data:
